version: "3.8"
services:
  sub-store:
    image: xream/sub-store:http-meta
    container_name: sub-store
    restart: always
    volumes:
      - ./data:/opt/app/data
    environment:
      - SUB_STORE_FRONTEND_BACKEND_PATH=/2cXaAxRGfddmGz2yx1wA
    ports:
      - 3001:3001
